    zn "%SYS"

    // Unexpire passwords and set up passwordless mode to simplify dev use.
    // ** Comment out these two line for Production use **
    do ##class(Security.Users).UnExpireUserPasswords("*")
    zpm "install passwordless"
    zpm "install language-extender"
    zpm "load /home/irisowner/dev/ -v":1
    set typ="F"
    set line=2
    set line(1)=" ; ? is JSON ? "
    set line(2)="#include ZZISJSON"
    set sc=$$cmd^zLangExtender(typ,"ZIJ",.line)	
    halt
